create sequence hibernate_sequence;

create table allowed_integrations_history (
    rev integer not null,
    integration_id1 bigint not null,
    integration_id2 bigint not null,
    revtype smallint,
    primary key (rev, integration_id1, integration_id2)
);

create table configuration_entity_history (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    role varchar(255),
    primary key (id, rev)
);

create table discovery_information_history (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    custom_display_name varchar(255),
    show_schools boolean,
    title varchar(255),
    primary key (id, rev)
);

create table discovery_information_excluded_schools_history (
    rev integer not null,
    discovery_information_id bigint not null,
    schools varchar(255) not null,
    revtype smallint,
    primary key (rev, discovery_information_id, schools)
);

create table discovery_information_schools_history (
    rev integer not null,
    discovery_information_id bigint not null,
    schools varchar(255) not null,
    revtype smallint,
    primary key (rev, discovery_information_id, schools)
);

create table identity_provider_history (
    configuration_entity_id bigint not null,
    rev integer not null,
    type varchar(31) not null,
    revtype smallint,
    encryption_certificate_valid_until DATE,
    entity_id varchar(255),
    flow_name varchar(255),
    wilma_hostname varchar(255),
    idp_id varchar(255),
    logo_url varchar(255),
    metadata_valid_until DATE,
    metadata_url varchar(255),
    signing_certificate_valid_until DATE,
    tenant_id varchar(255),
    primary key (configuration_entity_id, rev)
);

create table identity_provider_institution_types_history (
    rev integer not null,
    configuration_entity_id bigint not null,
    institution_type integer not null,
    revtype smallint,
    primary key (rev, configuration_entity_id, institution_type)
);

create table integration_history (
    id bigint not null,
    rev integer not null,
    revtype smallint,
    created_on timestamp,
    last_updated_on timestamp,
    acceptance_date date,
    deployment_date date,
    deployment_phase integer,
    service_contact_address varchar(255),
    configuration_entity_id bigint,
    discovery_information_id bigint,
    primary key (id, rev)
);

/*
create table revinfo (
    rev integer generated by default as identity,
    revtstmp bigint,
    primary key (rev)
);
*/
create table extended_revinfo (
    rev integer generated by default as identity,
    revtstmp bigint,
    user_id varchar(255),
    primary key (rev)
);

create table service_provider_history (
    configuration_entity_id bigint not null,
    rev integer not null,
    type varchar(31) not null,
    revtype smallint,
    client_id varchar(255),
    entity_id varchar(255),
    metadata_json text,
    name varchar(255),
    primary key (configuration_entity_id, rev)
);

create table integration_set_history (
       configuration_entity_id bigint not null,
        rev integer not null,
        revtype smallint,
        type varchar(255),
        name varchar(255),
        primary key (configuration_entity_id, rev)
);

create table integrations_sets_history (
       rev integer not null,
        integration_id bigint not null,
        integration_set_id bigint not null,
        revtype smallint,
        primary key (rev, integration_id, integration_set_id)
    );

alter table
    integration_set_history
add
    constraint FK2lkt0wnltd8fwkyt6c8151o3y foreign key (rev) references extended_revinfo;

alter table
    integrations_sets_history
add
    constraint FKnd3cfeul43swtk2g8h9ir8h4x foreign key (rev) references extended_revinfo;

alter table
    allowed_integrations_history
add
    constraint FK4eebjkc6cbma3wueeex0037id foreign key (rev) references extended_revinfo;

alter table
    configuration_entity_history
add
    constraint FKjhyu7400ilmve9fbgd3bn367d foreign key (rev) references extended_revinfo;

alter table
    discovery_information_history
add
    constraint FKfmmnf9kfh42q0a3j5sif75pp2 foreign key (rev) references extended_revinfo;

alter table
    discovery_information_excluded_schools_history
add
    constraint FKq3c63nj61xfpepymedwuar7s1 foreign key (rev) references extended_revinfo;

alter table
    discovery_information_schools_history
add
    constraint FKm32accej050me81m0i28k74uo foreign key (rev) references extended_revinfo;

alter table
    identity_provider_history
add
    constraint FK7w509xnson4xnuve0bkf5w2jg foreign key (rev) references extended_revinfo;

alter table
    identity_provider_institution_types_history
add
    constraint FKi0o8kawo25ruw6pwn0vbxan9v foreign key (rev) references extended_revinfo;

alter table
    integration_history
add
    constraint FKhy1vwg2qvt8lpc88n1eufvaob foreign key (rev) references extended_revinfo;

alter table
    service_provider_history
add
    constraint FKiom3u9dm02e44f1aywicrtqja foreign key (rev) references extended_revinfo;