create table discovery_information (
    id int8 generated by default as identity,
    custom_display_name varchar(255),
    title varchar(255),
    show_schools boolean not null,
    early_education_provider boolean not null,
    primary key (id)
);