create table if not exists integration (
    id int8 generated by default as identity,
    created_on timestamp,
    last_updated_on timestamp,
    deployment_phase int4 not null,
    acceptance_date date,
    deployment_date date,
    service_contact_address varchar(321),
    configuration_entity_id int8,
    discovery_information_id int8,
    organization_oid varchar(255),
    version int4,
    primary key (id)
);

alter table
    if exists integration
add
    constraint FKgevym9p3rbkgc4a5f4xo8wn2y foreign key (configuration_entity_id) references configuration_entity;

alter table
    if exists integration
add
    constraint FKpcfmomu6d464mkw7xiku4cb0g foreign key (discovery_information_id) references discovery_information;

alter table
    if exists integration
add
    constraint FKewd2fojvfrhpg19py0cjfgab4 foreign key (organization_oid) references organization;